# name = "Harsh deep"
# print=name

first_num= 10j
second_num = 20

third_num = 'singh'
print(type(first_num))
print(type(second_num))
print(type(third_num))
num_vari = 2003.3333
print(type(num_vari))

print(type(True))
a = 20
b = 30
c = 75
d = a+b+c
print("addition of three number are:",d)

e = a-b-c

print("subtraction of three number are:",e)
f = a/b
print("division of two number are:",f)
g = a%b
print("module of two number are",g)
h = a**b
print("exopnential of two number are",h)
